### ISSUE TITLE
Plugin throws NoSuchMethodError every 10 minutes

### ISSUE THREAD

**Issue by SullyTheUnusual** [meiskam/PlayerHeads#12]
https://hastebin.com/koyeyirova.bash

**Comment by crashdemons** [comment]
Does this issue still exist on newer versions (3.12.13 / 4.x) ?

**Comment by crashdemons** [comment]
If you still have this issue in a new version, please open a new issue - I can't reproduce the issue and your link appears to be dead since before I joined the project.
