### ISSUE TITLE
Running /ph spawn #<mob name> throws NPE

### ISSUE THREAD

**Issue by SullyTheUnusual** [meiskam/PlayerHeads#13]
https://hastebin.com/equgipefir.bash

**Comment by crashdemons** [comment]
Does this issue still exist on newer versions (3.12.13 / 4.x) ?

**Comment by crashdemons** [comment]
If you still have this issue in a new version, please open a new issue - I can't reproduce the issue and your link appears to be dead since before I joined the project.
