### ISSUE TITLE
NullPointerException in onPlayerInteractEvent

### ISSUE THREAD

**Issue by RainOfPain125** [meiskam/PlayerHeads#14]
https://pastebin.com/7SBwSZ57

git-Paper-1320
Plugins (74): ActionAnnouncer, AdvancedBan, AreaShop, ArrowTrails, Auctions, Autorank, AutoSaveWorld, BlowableObsidians, BuycraftX, CFD, Chairs, ChatFeelings, ChatItem, ChestRestock, Citizens, ColoredAnvils, CombatLogX, CompatNoCheatPlus, CoreProtect, CrazyCrates, CrazyEnvoy, DailyBonus, DeluxeJoin, DiscordSRV, EpicRename, Essentials, EssentialsChat, eZProtector, FactionChat, Factions, FactionsFly, HolographicDisplays, HolographicScoreboard, InfoBook, InventoryFull, LimitCrafting, LuckPerms, MassiveBooks, MassiveCore, mcMMO, mcMMOAction, MessageAnnouncer, MobArena, Multiverse-Core, NametagEdit, NoCheatPlus, NoPlugins, OldCombatMechanics, Orebfuscator4, PerWorldInventory, PlayerHeads, PluginLibrary, PowerNBT, ProtocolLib, React, ServerListPlus, ShopGUIPlus, ShulkerBlock, SilkSpawners, SilkSpawnersShopAddon, SimpleBackup, SuperbVote, SuperTrails, SuperVanish, Tablist, TitleManager, Trading, Vault, Votifier, WarningCategories, Wild, WorldBorder, WorldEdit, WorldGuard

**Comment by crashdemons** [comment]
Please test an updated build of 3.12.13, 3.12, or 4.x (master) and if the issue is fixed or not let me know.
