### ISSUE TITLE
Add mob spawner config option

### ISSUE THREAD

**Issue by TerdyTheTerd** [meiskam/PlayerHeads#25]
**Describe the solution you'd like**
Add a config option to not drop mob heads from mobs that were spawned from a mob spawner. This is to prevent mob heads from losing rarity easily with mob spawner farms, especially when using SilkSpawners or other such plugins.

**Additional context**
CreatureSpawnEvent store PersistentData via PersistentDataContainer class from Spigot-API if spawn reason is SPAWNER.
EntityDeathEvent check for PersistentData key that was set, return if set

I was implementing this myself, but I honestly cannot for the LIFE of me, get maven to behave and get spigot api added correctly. Build always fails because it cannot find the methods used in the above mentioned class.

**Comment by crashdemons** [comment]
noting your downstream issue crashdemons/PlayerHeads#77

**Comment by TerdyTheTerd** [comment]
Closing as this was implemented downstream I believe?

**Comment by crashdemons** [comment]
implemented, but hasn't been rigorously tested.
