### ISSUE TITLE
Charged Creeper Issue/Feature

### ISSUE THREAD

**Issue by TerdyTheTerd** [meiskam/PlayerHeads#26]
I feel like this is already a feature, but I cannot get other mobs to drop their heads when a charged creeper kills them, only the vanilla mobs (zombie/skelli etc) drop the heads. I tried using the different options in the config for charged creepers:
`vanilla|ignore|replace` and none of them seem to have any effect. I bumped up the modifier to a crazy number to ensure it would drop.

Am I missing something? Is this supposed to work?

**Comment by crashdemons** [comment]
it should work fine with `ignore` or `vanilla`.
`replace` would require that kills by mobs are allowed (mobpkonly: false)
(remember to use either /ph config set  or /ph config reload if you modify the config file itself)

I can verify that this is still working later on our server tomorrow, but in the past I've not had any issue with this working.


note: setting `chargedcreeperbehavior` to `vanilla` forces playerheads to avoid interacting with the drop at all - so mobs that normally drop heads would drop heads then.

**Comment by crashdemons** [comment]
test results on our server:
![image](https://user-images.githubusercontent.com/3233238/113820875-ea53e580-9740-11eb-9a8e-e19325c9b50d.png)
![image](https://user-images.githubusercontent.com/3233238/113820896-f475e400-9740-11eb-902a-5f0ba09e857c.png)
![image](https://user-images.githubusercontent.com/3233238/113820940-02c40000-9741-11eb-8c6b-1a7a2c2333d2.png)

**Comment by crashdemons** [comment]
We are using PlayerHeads version 5.2.15 (current snapshot) https://ci.meme.tips/job/PlayerHeads-5.x/1136/
this build should not contain significant changes to drop behaviors from 5.2.14
and here is our config: https://gist.github.com/crashdemons/d816d117bfd688c19fca0fc026fed53c

I was able to get a head drop with `ignore` regardless of chargedcreepermodifier or droprate (0.0 or 1.0) since the vanilla drop is ignored (allowed) with that behavior.

**Comment by TerdyTheTerd** [comment]
I will check back in when I have the time, I may have been missing the 
`mobpkonly: false` value. Thanks for the detailed response. A player and I spent hours gathering many of the more rare mobs so that we could finish our mob head collection, just for no heads to be dropped. I then tested several config options in creative to no avail, so hopefully with your post I can get them working as we need :D

**Comment by TerdyTheTerd** [comment]
There must be differences in the versions then, because using the above settings, and trying everything in between yields no non-vanilla mob head drops with a charged creeper. I reviewed your config as well and saw no discrepancies in settings other than the drop rates. I will update once I am able to update the servers plugin.

![image](https://user-images.githubusercontent.com/9743432/113949422-da85e100-97d4-11eb-9601-c1656451b395.png)
