### ISSUE TITLE
Rabbit skin has changed

### ISSUE THREAD

**Issue by TheBentoBox** [meiskam/PlayerHeads#7]
The skin of the player you are using for the rabbit mob head has been changed, making the mob not drop the appropriate head anymore.

As of 1.8, there are now features to use the skin textures cached with the Mojang skin servers so that you can get a head with a specific texture without relying on the player still having that skin. I believe switching to using these skin caching features would increase the longevity/stability of the plugin. Updates could be far less frequent.

**Comment by crashdemons** [comment]
4.x (master) now implements the textured head support you mention, I'll take a look at updating the heads for 3.x

**Comment by crashdemons** [comment]
I'm not sure what version this issue was made in, but `rabbit2077` used since 3.11 (and still in 3.12/3.12.13) still seems to use a rabbit skin.

MHF_Rabbit (unofficial) is a good alternative if we must change.

Let me know if you still have this issue in new versions.

**Comment by crashdemons** [comment]
If you still have the problem in an updated version (4.x) please open a new issue.
